export { getHotelsByPrice } from './price-range'
export { getHotelsByRoomsAndBeds } from './rooms-beds'
export { validateName } from './name-regex'
export { validateEmail } from './email-regex'
export { validatePassword } from './password-regex'
export { validateNumber } from './number-regex'
